In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('seaborn-deep')
import os
import pandas as pd
from numpy import mean
from numpy import std
from scipy.stats import shapiro
from scipy.stats import normaltest

In [2]:
data = pd.read_csv('data/main_players.csv')

In [3]:
data.isnull().sum()

Unnamed: 0                      0
ID                              0
Name                            0
Age                             0
Photo                           0
Nationality                     0
Flag                            1
Overall                         0
Potential                       0
Club                          156
Club Logo                       0
Value                           0
Wage                            0
Special                         0
Preferred Foot                  0
International Reputation        0
Weak Foot                       0
Skill Moves                     0
Work Rate                       0
Body Type                       0
Real Face                       0
Position                        0
Jersey Number                   0
Joined                       1090
Loaned From                 11946
Contract Valid Until          156
Height                          0
Weight                          0
LS                              0
ST                              0
                            ...
Curve                           0
FKAccuracy                      0
LongPassing                     0
BallControl                     0
Acceleration                    0
SprintSpeed                     0
Agility                         0
Reactions                       0
Balance                         0
ShotPower                       0
Jumping                         0
Stamina                         0
Strength                        0
LongShots                       0
Aggression                      0
Interceptions                   0
Positioning                     0
Vision                          0
Penalties                       0
Composure                       0
Marking                         0
StandingTackle                  0
SlidingTackle                   0
GKDiving                        0
GKHandling                      0
GKKicking                       0
GKPositioning                   0
GKReflexes                      0
Release Clause               1097
pozicija                        0
Length: 90, dtype: int64

In [4]:
data.describe()

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,...,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000,12880.000000
mean,6457.166693,215209.735559,24.962655,66.469953,71.570963,1666.689674,1.115528,3.005280,2.531755,19.351009,...,52.130901,60.313898,51.306910,51.832220,49.600078,10.464441,10.560093,10.547050,10.525000,10.520652
std,3736.618283,28628.372123,4.548545,6.796536,6.034680,195.845986,0.396241,0.635153,0.616630,15.612773,...,12.525081,10.146293,17.218874,19.215458,19.186598,3.083431,3.063141,3.117861,3.072688,3.100693
min,0.000000,16.000000,16.000000,46.000000,48.000000,1000.000000,1.000000,1.000000,2.000000,2.000000,...,13.000000,22.000000,10.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3221.750000,201143.750000,21.000000,62.000000,67.000000,1527.000000,1.000000,3.000000,2.000000,8.000000,...,42.000000,53.000000,37.000000,35.000000,32.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6446.500000,222194.500000,25.000000,66.000000,71.000000,1669.000000,1.000000,3.000000,2.000000,17.000000,...,52.000000,61.000000,56.000000,59.000000,56.000000,10.000000,11.000000,11.000000,11.000000,11.000000
75%,9707.250000,236695.250000,28.000000,71.000000,75.000000,1804.000000,1.000000,3.000000,3.000000,25.000000,...,62.000000,67.000000,65.000000,67.000000,65.000000,13.000000,13.000000,13.000000,13.000000,13.000000
max,12945.000000,246620.000000,41.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,32.000000,33.000000,41.000000,33.000000,37.000000